name: InventoryLogs
version: ${project.version}
main: pl.workonfire.inventorylogs.InventoryLogs
api-version: 1.13
authors: [workonfire]
commands:
  forcesave:
    description: "A force save command for InventoryLogs."